// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCexPBEkxWmIBNb_ic6rv0cvfnR_DXrKJQ',
    appId: '1:227368534831:android:4e87149b4f7a10b710d7da',
    messagingSenderId: '227368534831',
    projectId: 'arrow-escape-c84f2',
    storageBucket: 'arrow-escape-c84f2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummy_ArrowEscape_IOSKey',
    appId: '1:123456789012:ios:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'arrow-escape-dummy',
    storageBucket: 'arrow-escape-dummy.appspot.com',
    iosBundleId: 'com.arrow.escape.arrowEscape',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummy_ArrowEscape_WebKey',
    appId: '1:123456789012:web:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'arrow-escape-dummy',
    storageBucket: 'arrow-escape-dummy.appspot.com',
    authDomain: 'arrow-escape-dummy.firebaseapp.com',
  );
}
